version: 1.0.{build}
branches:
  only:
    - "release"
build_cloud: GCE
image: Visual Studio 2022
cache:
  - 'C:\Users\Public\Documents\dotnet_install\.nuget\packages'
clone_depth: 3
clone_folder: C:\Users\Public\appveyor\Snap.Hutao
install:
- ps: |
    Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -UseBasicParsing -OutFile "$env:temp\dotnet-install.ps1"
    & $env:temp\dotnet-install.ps1 -Architecture x64 -Channel '10.0' -InstallDir "$env:ProgramFiles\dotnet"
- pwsh: dotnet tool restore
before_build:
  - cmd: dotnet --version
build_script:
- pwsh: dotnet cake
artifacts:
- path: src/output/*.msix
  type: file
deploy:
- provider: Webhook
  url: https://app.signpath.io/API/v1/7a941fa3-64d8-4c45-bd03-92a02bcd4964/Integrations/AppVeyor?ProjectSlug=Snap.Hutao&SigningPolicySlug=release-signing&ArtifactConfigurationSlug=msix
  authorization:
    secure: j8srQ5/UYWhI+jlm3Vo3D3QfXoRyQ9hOn3ynJGtwusKui4+uDi4gykdUFYCITZxK+C/fOCAZNJ+YaKSm/OaiXw==
